export const TOGGLE_PAGE = 'TOGGLE_PAGE';
export const SET_SPIELFIGUR_POSITION = 'SET_SPIELFIGUR_POSITION';
export const SET_POPUP = 'SET_POPUP';
export const SET_GEWUERFELTE_ZAHL = 'SET_GEWUERFELTE_ZAHL';
export const FETCH_FRAGEN = 'FETCH_FRAGEN';